import { Campaign } from "./types";
import { TimelineEvent, Timelines } from "./types";

export const campaign: Campaign = {
  agency: false,
  blitz_autocampaign: true,
  brief: "testing timelines feature",
  campaign_manager: {
    email: "win@thecultureclub.us",
    name: "Houston Roa",
    phone_number: "",
  },
  campaign_status: "Draft",
  campaign_sum: 240,
  campaign_type: "",
  campany_id: 1,
  creators: [
    {
      code: "HEAJGLMGR",
      creator_details: {
        avg_turnaround_time_days: null,
        avg_views: null,
        blitz_score: null,
        creator: "thealexroa",
        creator_type: "creator",
        date_added: "Tue, 07 May 2024 00:00:00 GMT",
        dedicated: null,
        email: "alexroa181@gmail.com",
        flag_notes: null,
        geolocation_gender_ethnicity: "HTX / Male / White",
        ig_feed_post: "200",
        ig_reels_brand: "200",
        ig_reels_sound: "100",
        ig_stories_bundle: null,
        ig_story: null,
        instagram: "2586",
        instagram_link: "https://www.instagram.com/thealexroa",
        integration_3045s: null,
        integration_3m: null,
        integration_60s: "",
        integration_90s: null,
        is_vendor: false,
        last_contact: null,
        last_inbound: null,
        last_rate_presented: "240",
        last_rate_taken: null,
        last_updated: "Thu, 01 Aug 2024 00:00:00 GMT",
        last_updated_insight: "Fri, 12 Jul 2024 15:58:36 GMT",
        manager: "TCC",
        mediakit: null,
        notes_content_style: "tell us about yourself",
        payout_email: "alex@thecultureclub.us",
        pfphref:
          "https://voyagehouston.com/wp-content/uploads/2022/04/c-AlexRoa__IMG7255_1648065915331.jpg",
        phone_number: "8329714777",
        primary_market: "Travel",
        promos_completed: null,
        promos_pitched: 20,
        promos_sent: "",
        public: [
          {
            audience_data: [
              {
                age_range: "13-17",
                gender: "MALE",
                value: 8.8681,
              },
              {
                age_range: "18-24",
                gender: "MALE",
                value: 49.1778,
              },
              {
                age_range: "25-34",
                gender: "MALE",
                value: 11.2867,
              },
              {
                age_range: "35-44",
                gender: "MALE",
                value: 0.8062,
              },
              {
                age_range: "13-17",
                gender: "FEMALE",
                value: 3.6416,
              },
              {
                age_range: "18-24",
                gender: "FEMALE",
                value: 16.7514,
              },
              {
                age_range: "25-34",
                gender: "FEMALE",
                value: 9.4682,
              },
            ],
            average_comments: 0,
            average_likes: 0,
            average_views: 0,
            country_data: [
              {
                code: "US",
                value: 84.9711,
              },
              {
                code: "GB",
                value: 2.8902,
              },
              {
                code: "MX",
                value: 1.7341,
              },
              {
                code: "PH",
                value: 1.7341,
              },
              {
                code: "NG",
                value: 1.1561,
              },
              {
                code: "CA",
                value: 1.1561,
              },
              {
                code: "DE",
                value: 0.578,
              },
            ],
            creator_id: "thealexroa",
            failure_reason: null,
            platform: {
              id: 1,
              insight_id: "de55aeec-0dc8-4119-bf90-16b3d1f0c987",
              key: "tk",
              name: "TikTok",
            },
            platform_id: 1,
          },
          {
            audience_data: [
              {
                age_range: "13-17",
                gender: "MALE",
                value: 2.142,
              },
              {
                age_range: "18-24",
                gender: "MALE",
                value: 24.4439,
              },
              {
                age_range: "25-34",
                gender: "MALE",
                value: 14.49,
              },
              {
                age_range: "35-44",
                gender: "MALE",
                value: 2.646,
              },
              {
                age_range: "45-64",
                gender: "MALE",
                value: 1.638,
              },
              {
                age_range: "13-17",
                gender: "FEMALE",
                value: 3.9981,
              },
              {
                age_range: "18-24",
                gender: "FEMALE",
                value: 27.1663,
              },
              {
                age_range: "25-34",
                gender: "FEMALE",
                value: 21.6305,
              },
              {
                age_range: "35-44",
                gender: "FEMALE",
                value: 1.6402,
              },
              {
                age_range: "45-64",
                gender: "FEMALE",
                value: 0.205,
              },
            ],
            average_comments: 24,
            average_likes: 0,
            average_views: 0,
            country_data: [
              {
                code: "US",
                value: 93.1142,
              },
              {
                code: "BR",
                value: 2.3474,
              },
              {
                code: "CA",
                value: 0.626,
              },
              {
                code: "RU",
                value: 0.4695,
              },
              {
                code: "DE",
                value: 0.313,
              },
              {
                code: "AE",
                value: 0.313,
              },
              {
                code: "MX",
                value: 0.313,
              },
            ],
            creator_id: "thealexroa",
            failure_reason: null,
            platform: {
              id: 2,
              insight_id: "9bb8913b-ddd9-430b-a66a-d74d846e6c66",
              key: "ig",
              name: "Instagram",
            },
            platform_id: 2,
          },
        ],
        rate_2530s: "",
        region: "NACAUKAUS",
        shorts: "",
        snap: null,
        snap_link: null,
        snapchat_story_post: null,
        status: "Associate",
        superviser: "",
        tiktok: "604",
        tiktok_brand: "200",
        tiktok_link: "https://www.tiktok.com/@thealexroa",
        tiktok_sound: "100",
        total_inbound: null,
        total_paid_inbound: null,
        tweet: null,
        tweet_repost: null,
        twitch: null,
        twitch_link: null,
        twitter: null,
        twitter_link: null,
        youtube: undefined,
        youtube_link: undefined,
      },
      following: "604",
      id: "thealexroa",
      name: "thealexroa",
      offerSent: true,
      pfphref:
        "https://voyagehouston.com/wp-content/uploads/2022/04/c-AlexRoa__IMG7255_1648065915331.jpg",
      platformLink: "https://www.tiktok.com/@thealexroa",
      price: 240,
      promotionPlatform: "TikTok",
      promotionType: "Brand",
      status: "Accepted",
      submissionLink:
        "https://drive.google.com/drive/folders/1xiQvjMWf1UFTRUGwarPEWwlrTGQacVqF",
      assetsSent: false,
      assetsApproved: false,
      skipPayout: false,
      creatorBrief: "",
      postingInstructions: "",
      boostCode: "",
    },
    {
      code: "ERE6NG4LS",
      creator_details: {
        avg_turnaround_time_days: null,
        avg_views: null,
        blitz_score: null,
        creator: "jeremycrandall",
        creator_type: "creator",
        date_added: "Mon, 29 Jan 2024 00:00:00 GMT",
        dedicated: null,
        email: "jc@thecultureclub.us",
        flag_notes: null,
        geolocation_gender_ethnicity: "USA / NY / Male",
        ig_feed_post: "",
        ig_reels_brand: "",
        ig_reels_sound: "",
        ig_stories_bundle: "",
        ig_story: null,
        instagram: "",
        instagram_link: "",
        integration_3045s: null,
        integration_3m: null,
        integration_60s: "",
        integration_90s: null,
        is_vendor: false,
        last_contact: null,
        last_inbound: null,
        last_rate_presented: "240",
        last_rate_taken: null,
        last_updated: "Mon, 29 Jan 2024 00:00:00 GMT",
        last_updated_insight: "Fri, 12 Jul 2024 15:58:36 GMT",
        manager: "TCC",
        mediakit: null,
        notes_content_style: "",
        payout_email: "",
        pfphref:
          "https://media.licdn.com/dms/image/D5603AQEiiUdykNURgg/profile-displayphoto-shrink_200_200/0/1709318860183?e=2147483647&v=beta&t=bazjft_lQJWWhYsGRqR_25UmA_B6TQtEQfjr6eUlQjA",
        phone_number: "15854904933",
        primary_market: "Comedy",
        promos_completed: null,
        promos_pitched: 2,
        promos_sent: "7",
        public: [],
        rate_2530s: "",
        region: "NACAUKAUS",
        shorts: "",
        snap: null,
        snap_link: null,
        snapchat_story_post: null,
        status: "Associate",
        superviser: "AlitoCCMC",
        tiktok: "600",
        tiktok_brand: "1",
        tiktok_link: "https://www.tiktok.com/@jeremycrandall",
        tiktok_sound: "1",
        total_inbound: null,
        total_paid_inbound: null,
        tweet: null,
        tweet_repost: null,
        twitch: null,
        twitch_link: null,
        twitter: null,
        twitter_link: null,
        youtube: "",
        youtube_link: "",
      },
      following: "600",
      id: "jeremycrandall",
      name: "jeremycrandall",
      offerSent: true,
      pfphref:
        "https://media.licdn.com/dms/image/D5603AQEiiUdykNURgg/profile-displayphoto-shrink_200_200/0/1709318860183?e=2147483647&v=beta&t=bazjft_lQJWWhYsGRqR_25UmA_B6TQtEQfjr6eUlQjA",
      platformLink: "https://www.tiktok.com/@jeremycrandall",
      price: 100,
      promotionPlatform: "TikTok",
      promotionType: "Brand",
      assetsSent: false,
      assetsApproved: false,
      skipPayout: false,
      creatorBrief: "",
      postingInstructions: "",
      boostCode: "",
    },
    {
      code: "ODYKHZN0W",
      creator_details: {
        avg_turnaround_time_days: null,
        avg_views: null,
        blitz_score: null,
        creator: "codytc",
        creator_type: "creator",
        date_added: "Mon, 22 Jul 2024 00:00:00 GMT",
        dedicated: null,
        email: "codytc.inquiries@gmail.com",
        flag_notes: null,
        geolocation_gender_ethnicity: "New York / Male / White",
        ig_feed_post: "",
        ig_reels_brand: "",
        ig_reels_sound: "",
        ig_stories_bundle: null,
        ig_story: null,
        instagram: "",
        instagram_link: "",
        integration_3045s: null,
        integration_3m: null,
        integration_60s: "",
        integration_90s: null,
        is_vendor: false,
        last_contact: null,
        last_inbound: null,
        last_rate_presented: "240",
        last_rate_taken: null,
        last_updated: "Thu, 01 Aug 2024 00:00:00 GMT",
        last_updated_insight: "Mon, 22 Jul 2024 20:58:03 GMT",
        manager: "TCC",
        mediakit: null,
        notes_content_style: "Content creator of satirical Discord memes",
        payout_email: "cody@vegamedia.io",
        pfphref: "",
        phone_number: "5854551369",
        primary_market: "Comedy",
        promos_completed: null,
        promos_pitched: 1,
        promos_sent: "",
        public: [],
        rate_2530s: "",
        region: "NACAUKAUS",
        shorts: "800",
        snap: null,
        snap_link: null,
        snapchat_story_post: null,
        status: "Partner",
        superviser: "",
        tiktok: "",
        tiktok_brand: "",
        tiktok_link: "",
        tiktok_sound: "",
        total_inbound: null,
        total_paid_inbound: null,
        tweet: null,
        tweet_repost: null,
        twitch: null,
        twitch_link: null,
        twitter: null,
        twitter_link: null,
        youtube: "155,000",
        youtube_link: "https://www.youtube.com/@CodyTC",
      },
      following: "147,000",
      id: "codytc",
      name: "codytc",
      offerSent: true,
      pfphref: "",
      platformLink: "https://www.youtube.com/@CodyTC",
      price: 960,
      promotionPlatform: "Youtube",
      promotionType: "shorts",
      assetsSent: false,
      assetsApproved: false,
      skipPayout: false,
      creatorBrief: "",
      postingInstructions: "",
      boostCode: "",
    },
  ],
  drive_link:
    "https://drive.google.com/drive/folders/1zM5RvgSwKj9m-6aUoTeAMxp6vmy3mKzr",
  finish_date: "Tue, 23 Jul 2024 00:00:00 GMT",
  id: 292,
  ideal_duedate: "Wed, 31 Jul 2024 00:00:00 GMT",
  invoice_date: "Tue, 23 Jul 2024 00:00:00 GMT",
  name: "test timelines",
  paid_date: "Tue, 23 Jul 2024 00:00:00 GMT",
  po_number: "",
  proposal_date: "Tue, 23 Jul 2024 18:33:21 GMT",
  shared_with: null,
  tools: [],
  user_id: 1,
  video_amount: 1,
};

export const timelineEvents: TimelineEvent[] = [
  {
    campaign_id: 292,
    id: 17,
    last_updated: "Tue, 23 Jul 2024 18:34:07 GMT",
    last_user_updated: null,
    manager_completed: false,
    notes: "",
    objective: "script for video done",
    projected_date: "Wed, 24 Jul 2024 05:00:00 GMT",
    status: "incomplete",
    username: "thealexroa",
    will_delete: false,
  },
  {
    campaign_id: 292,
    id: 18,
    last_updated: "Tue, 23 Jul 2024 18:34:07 GMT",
    last_user_updated: null,
    manager_completed: false,
    notes: "",
    objective: "draft for video done",
    projected_date: "Fri, 26 Jul 2024 05:00:00 GMT",
    status: "incomplete",
    username: "thealexroa",
    will_delete: true,
  },
];
